### ISSUE TITLE
Repeatedly opening new Taskbar-groups

### ISSUE THREAD

**Issue by aemdca4** [tjackenpacken/taskbar-groups#127] opened 2021-05-12 15:14 UTC
Hey Guys,

when I launch Taskbar-Groups it will Repeatedly open itself so far that it freezes my PC.
Does anyone else have this problem?

**Comment by PikeNote** [comment] 2021-05-13 02:49
Duplicate of #94

**Closed as completed** 2021-06-02 14:39 UTC
