### ISSUE TITLE
[Bug] Does not work if the taskbar is moved to the top of the screen

### ISSUE THREAD

**Issue by mazenbesher** [tjackenpacken/taskbar-groups#6] opened 2020-12-17 20:35 UTC

**Comment by MostHated** [comment] 2020-12-17 23:46
Yeah, that is unfortunate. I came here for the same reason. Though, if the taskbar is at the top, could just set the position to a negative value instead of positive if the position is determined based on the taskbar itself being the origin? I have not looked over the code yet, so not sure, just a guess.

**Comment by innuendo33** [comment] 2020-12-18 08:20
Same here , would you please fix it for top taskbar users ?  otherwise nice app !

**Comment by zsotroav** [comment] 2020-12-18 09:09
Does not work with the taskbar on the side either.

**Comment by Darthagnon** [comment] 2020-12-18 12:14
Should be an easy-ish fix, judging by Issue #2 - possibly just adapted presets for Top/bottom/left/right taskbars and [mathematically reading the taskbar location](https://stackoverflow.com/questions/1264406/how-do-i-get-the-taskbars-position-and-size)

**Comment by MostHated** [comment] 2020-12-19 06:47
Good deal. It does seem to be working now. One thing I noticed though, if you click it then move the mouse away, the icons appear around wherever the mouse is after X amount of time. Not sure if that is intended?

**Comment by mazenbesher** [comment] 2020-12-19 07:40
![taskbar-groups-bug](https://user-images.githubusercontent.com/1931989/102684064-bd051b00-41d5-11eb-8db8-24eb2bdd6686.gif)
I don't think that this is the intended behavior 😓

**Comment by innuendo33** [comment] 2020-12-21 09:52
Thank you tjackenpacken for fixing that ! 
Otherwise , would it be possible in further updates to add app names when mouse hovering on icons , could be confusing when lot of cluttered icons :)

**Comment by Darthagnon** [comment] 2020-12-21 12:00
@mazenbesher I don't think that's intended behaviour, but a side-effect of how it makes the box appear - it calculates where your mouse is on the taskbar and draws the box right above it (this is because it isn't possible to read from Windows where something is pinned). Normally, it should appear instantly and you won't notice that. By the looks of it, if you're fast enough with the mouse, or your system is slow enough (e.g. high load) then the box can get drawn incorrectly.

I tinkered with another C# program that draws boxes onscreen and it had a workaround by setting its own process priority to High.

**Comment by tjackenpacken** [comment] 2020-12-21 20:55
> 
> 
> Good deal. It does seem to be working now. One thing I noticed though, if you click it then move the mouse away, the icons appear around wherever the mouse is after X amount of time. Not sure if that is intended?

As Darthagnon mentioned this is not intended but it's hard to avoid. I'm gonna look over the priority if that could help.

Since the initial issue has been resolved though the latest releases im closing this issue!

**Closed by tjackenpacken** 2020-12-21 20:55 UTC
