### ISSUE TITLE
{Feature Request] Allow editing groups

### ISSUE THREAD

**Issue by Andrew6rant** [tjackenpacken/taskbar-groups#17] opened 2020-12-20 21:56 UTC
Right now, you are unable to edit already-made groups, you have to delete and remake a group if you want to add another program to it.

EDIT: nvm, I saw this on the to-do list already

**Comment by Darthagnon** [comment] 2020-12-21 12:01
Duplicate of #9

**Comment by tjackenpacken** [comment] 2020-12-21 21:07
Sorting and editing of groups has been included in the latest release (v0.1.4)!

**Closed by tjackenpacken** 2020-12-21 21:07 UTC
